export const testFuncEmul = true;

export const FACE_DETECT = {
    title: '人脸识别登录', 
    text1: '请将脸部置于堤示框内, 平视屏慕, 并正对光源',
    text2: '请勿遮挡面部',
    successText: '验证成功',
    failureText1: '人脸验证失败!',
    failureText2: '请正对屏幕, 验部不要有遮挡',
    failureTryButton: '重新识别人脸登录',
    failureDifMethod: '使用其他登录方式'
}

export const RESET_PWD = {
    title: '手机号找回密码',
    actionBtnTitle: '人脸找回密码',
    phoneNumber: '手机号',
    phoneNumberPlaceHolder: '请输入您的手机号',
    verifyCode: '验证码',
    verifyCodePlaceHolder: '请输入您的验证码',
    newPass: '新密码',
    newPassPlaceHolder: '请输没置的新密码',
    reWritePass: '确认密码',
    reWritePassPlaceHolder: '再次输入您的新密码',
    conformBtn: '确认修改',
    sendVerifyBtn: '获取验证码',
    successText: '密码修改成功',
    useText: '请使用新密码登录',
    confirm: '登录'
}

export const NEXT_BTN = {
    title: '下一步',
}

export const PROJNAME = {
    title: 'Manage', 
    content: '浦口高新区南大化工厂'
}

export const SIGN = {
    title: '注册',
    title1: '人脸釆集',
    title2: '身份证釆集',
    title3: '人证照片釆集',
    progress_1: '基本信息',
    progress_2: '实名认证',
    progress_3: '身份验证',
    progress_4: '完成',
    pass: '没置登录密码',
    passPlaceHolder: '请没置您的密码',
    reWritePass: '确认密码',
    reWritePassPlaceHolder: '再次输入您的密码',
    message: '已有账号, 立即登录',
    footer: '我已阅读并同意 《Manage隐私政策》',
    passInputError: '两次密码输入的不一致, 请重新输入',
    name: '姓名',
    namePlaceHolder: '请输入您的真实姓名',
    verifyCode: '身份证号码',
    verifyCodePlaceHolder: '请输入您的身份证号码',
    range: '有效期限',
    rangeFromPlaceHolder: '请选择开始日期',
    rangeToPlaceHolder: '请选择结束日期',
    photoUploadText: '拍摄您本人人脸, 请确保:',
    photoUploadText1: '1.由本人完成',
    photoUploadText2: '2.请将脸部置于提示框内',
    photoUploadText3: '3.平视屏慕并正对光源',
    photoUploadConfirm: '釆集本人人脸',
    photoUploadSuccess: '釆集成功',
    FailureText1: '没有认出你',
    FailureText2: '正对手机，更容易成功',
    FailureTryBtn: '再试一次',
    FailureCancelBtn: '退出',
    cardUploadText1: '拍摄身份证正面',
    cardUploadText2: '拍摄身份证反面',
    cardUploadText3: '请确保：',
    cardUploadText4: '1.证件信息请晰可见,四角完整',
    cardUploadText5: '2.签发单位, 有效期等信息请晰无误',
    photoIdUploadText1: '手持身份证拍摄',
    photoIdUploadText2: '请确保:',
    photoIdUploadText3: '1.身份证上的所有信息清晰可见',
    photoIdUploadText4: '2.手持证件人需免冠，五官清晰，建议未化妆',
    photoIdUploadText5: '3.照片内容真实有效，不得做任何修改',
    dateCancel: '取消',
    dateConfirm: '确定',
    dateTitle: '请选择日期',
}

export const SAFETY_STUDY = {
    title: '安全学习',
    content: '视频计时学习',
    movie: '视频',
    text: '文章',
    movieTitle: '视频名称:',
    studyLen: '学习时长:',
    cell1: '全部',
    cell2: '未学习',
    cell3: '正在学习',
    cell4: '已学完',
    timeLength: '时长:',
    itemTitle: '关于化工场地安全问题',
    docTitle: '倒计时：'
}

export const ASK_ANSWER = {
    title: '答题',
    title1: '人脸识别', 
    content: '计时答题得分',
    cell1: '全部',
    cell2: '未答题',
    cell3: '合格',
    cell4: '不合格',
    itemTitle: '关于化工场地安全问题',
    text1: '请将脸部置于堤示框内, 平视屏慕, 并正对光源',
    text2: '请勿遮挡面部',
    beforeText: '识别当前人脸',
    successText: '验证成功',
    failureText1: '人脸验证失败!',
    item1: '考试题库',
    item2: '考试提数',
    item3: '单题计时',
    itemText1: '题/',
    itemText2: '题 (随机)',
    criteria1: '单题倒计时',
    criteria2: '秒答题，答对大于等于',
    criteria3: '题为合格，少于',
    criteria4: '题不合格',
    button1: '开始答题',
    button2: '下一题',
    button3: '返回',
    solTitle: '倒计时：',
    solState: '已答题',
    failureText2: '您还有10道题没做,确认',
    failureText3: '退出码?',
    confirm: '确定',
    cancel: '取消',
    resultSuccess: '(成绩合格)',
    resultFailure: '(成绩不合格)',
    didNotCount: '未答题数',
    errorCount: '错题数',
    rightCount: '答对题数',
}

export const SHORT_ALARM = {
    title: '一键报警',
    content: '紧急撤离消息',
    confirmText: '确认报警',
    connecting: '连接中…',
    disconnect: '挂断',
}

export const SELCHECK_LOG = {
    title: '抽检记录',
    title1: '抽检视频记录',
    content: '查看抽检视频',
    manager: '管理员',
    state: '邀请您视频抽检',
    recieve: '接受',
    chkManager: '抽检管理员:',
    chkTime: '抽检时间:',
    cell1: '全部',
    cell2: '合格',
    cell3: '不合格',
    cell4: '未接通',
    detail: '抽检视频详情',
    note: '备注:',
    detailNote: '关于抽检视频的信息及整改建议',
}

export const MESSAGE = {
    title: '我要举报',
    content: '举报不良事件',
    item1: '我的举报',
    text: '举报内容:',
    placeFolder: '清输入举报内容',
    text1: '上传证书:',
    text2: '(上传视频或者图片)',
    text3: '提交',
    buttonRemove: '删除',
    modalTitle: '是否删除该条举报记录?',
    title1: '举报洋情',
}

export const ONLINE_TALK = {
    title: '在线咨询',
    title1: '我要咨询',
    title2: '我的咨询',
    button: '提交',
    text: '咨询问题:',
    placeFolder: '请输入您的咨询问题...',
    text1: '问题洋情:',
    placeFolder1: '请详细描述您的问题...',
    buttonRemove: '删除',
    modalTitle: '是否删除全部咨询信息?',
    return: '回复',
    pairMe: '我：',
    pairManager: '安监管理局：',
    placeholder: '请输入回复信息',
}

export const EQUIPSTATE = {
    title: '设备状态',
    title1: '审核详情',
    title2: '相机胶卷',
    cell1: '全部',
    cell2: '设备报废',
    cell3: '设备检修',
    cell4: '设备维护',
    cell5: '正常设备',
    text1: '去检修',
    text2: '去维护',
    item1: '上传时间: ',
    item2: '合格',
    item3: '不合格',
    item4: '审批意见',
    item5: '拍摄',
    button: '重新检修',
    confirm: '确定',
    recordStart: '点击开始拍摄',
    recordStop: '结束拍摄',
    browser: '预览',
}

export const MYPAGE = {
    title_placeholder: '我的',
    card: '身份证',
    tel: '联系电话',
    education: '文化程度',
    address: '籍贯',
    signManagement: '手写签名管理',
    salary: '工资记录',
    vocationTech: '职业技能',
    addressBook: '从业记录',
    educationHistory: '培训记录',
    awadingInfo: '诚信信息',
    workKind: '部门',
    plant: '职位',
    editMessage: '是否确认退出账户?',
    myInfoEditTitle: '资料修改',
    myPhoto: '我的头像',
    myName: '我的姓名',
    mySex: '我的性别',
    myCardNum: '身份证号',
    myBirthday: '出生日期',
    educationPlaceHolder: '请选择您的文化程度',
    myAddress: '家庭住址',
    myAddressPlaceHolder1: '请选择所在地区',
    myAddressPlaceHolder2: '请输入您的详细现居住址',
    myFatherBirthPlace: '籍贯',
    myFatherBirthPlacePlaceHolder: '请选择籍贯',
    myAgent: '紧急联络人',
    myAgentTel: '紧急联络人电话',
    myPhotoEditTitle: '匹配人脸照片',
    myPhotoEditText1: '请将脸部置于堤示框内, 平视屏慕, 并正对光源',
    myPhotoEditText2: '完成随机脸部动作',
    myPhotoEditText3: '识别当前人脸',
    myPhotoEditSuccessMsg1: '匹配成功',
    myPhotoEditTitle1: '采集人脸照片',
    myPhotoEditText4: '请勿遮挡面部',
    myPhotoEditText5: '采集新人脸',
    myPhotoEditSuccessMsg2: '修改成功',
    myPhoneNumEdit: '更换手机号码',
    myPhoneNumEditMsg1: '没有认出你',
    myPhoneNumEditMsg2: '正对手机, 更容易成功',
    myPhoneOldNum: '手机号码:',
    myPhoneNewNum: '更换手机号码:',
    myPhoneNewNumPlaceHolder: '请输入您的手机号码',
    myPhoneNewNumVerifyText1: '我们已发送验证号短信到您的手机:',
    myPhoneNewNumVerifyText2: '重新发新',
    myPhoneNewNumVerifyText3: '收不到验证号短信? 重新获取',
    myPhoneNewNumVerifyText4: '已经成功更换手机号码',
    myPhoneNewNumVerifyText5: '下次请使用手机号',
    myPhoneNewNumVerifyText6: '登录',
    myPhoneNewNumVerifyText7: '登录密码不变',
    addressBookItemName: '项目名称',
    addressBookItemTitle1: '岗位信息',
    itemInfo: '项目信息',
    joinCardNum: '身份证号',
    joinSalary: '薪资',
    joinPlant: '岗位详请',
    joinConfirmBtn: '代入手写签名', 
    techName: '证书名称: ',
    techNamePlaceHolder: '请输入您的证书名称',
    techNumber: '证书编号: ',
    techNumberPlaceHolder: '请输入您的证书编号',
    techDate: '有效期: ',
    techDate1: '证书有效期: ',
    techDatePlaceHolder: '请选择获得证书的时间',
    techPhoto: '上传证书:',
    techPhotoPlaceHolder1: '证书封面照片',
    techPhotoPlaceHolder2: '证书内页照片',
    eduName: '培训名称',
    eduNamePlaceHolder: '请输入您的培训名称',
    eduDate: '培训起止时间',
    eduDatePlaceHolder1: '起:',  
    eduDatePlaceHolder2: '止:',  
    eduPlace: '培训地点',
    eduPlacePlaceHolder: '请输入您的受培训地点',
}

export const COMMON = {
    select: '请选择', 
    startTime: '开始时间',
    endTime: '结束时间',
    timeLength: '时长(小时)',
    time: '小时',
    all: '全部',
    checking: '待审批',
    passCheck: '已审批',
    cancelCheck: '已撤销',
    ok: '确定',
    ok2: '确认',
    cancel1: '取消',
    cancel: '撤销',
    send: '提交',
    delete: '删除',
    answer: '回复',
    inputPlaceholder: '请输入',
    save: '保仔',
    moneyUnit: '元', 
    detail: '详情',
    name: '姓名',
    clear: '清除',
    ok1: '确认无误',
    add: '添加',
}

export const DROPDOWNS = {
    equipInfoDegree: [{
        '1级': {name: '1级'},
        '2级': {name: '2级'},
        '3级': {name: '3级'},
        '4级': {name: '4级'},
        '5级': {name: '5级'},
        '6级': {name: '6级'},
        '7级': {name: '7级'},
        '8级': {name: '8级'},
        '9级': {name: '9级'},
        '10级': {name: '10级'}
    }],
    equipInfoUseYears: [{
        '1年': {name: '1年'},
        '2年': {name: '2年'},
        '3年': {name: '3年'},
        '4年': {name: '4年'},
        '5年': {name: '5年'},
        '6年': {name: '6年'},
        '7年': {name: '7年'},
        '8年': {name: '8年'},
        '9年': {name: '9年'},
        '10年': {name: '10年'},
        '11年': {name: '11年'},
        '12年': {name: '12年'},
        '13年': {name: '13年'},
        '14年': {name: '14年'},
        '15年': {name: '15年'},
        '16年': {name: '16年'},
        '17年': {name: '17年'},
        '18年': {name: '18年'},
        '19年': {name: '19年'},
        '20年': {name: '20年'},
    }],
    nationality: [{
        '汉族': {name: '汉族'},
        '满族': {name: '满族'},
        '藏族': {name: '藏族'},
    }],
    education_level: [{
        '博士': {name: '博士'},
        '硕士': {name: '硕士'},
        '本科': {name: '本科'},
        '大专': {name: '大专'},
        '中专': {name: '中专'},
        '中技': {name: '中技'},
        '技工学校': {name: '技工学校'},
        '高中': {name: '高中'},
        '初中': {name: '初中'},
        '小学': {name: '小学'},
        '文盲': {name: '文盲'},
        '半文盲': {name: '半文盲'},
        ' ': {name: ' '},
        '  ': {name: '  '},
    }],
    province_city: [
        {name: '辽宁省', id: '10',
            children: [
                {name: '沈阳市', id: '101', children: [{name: '沈阳区', id: '101'}, {name: '大连区', id: '102'}]},
                {name: '大连市', id: '102', children: [{name: '沈阳区', id: '101'}, {name: '大连区', id: '102'}]},
                {name: '丹东市', id: '103', children: [{name: '沈阳区', id: '101'}, {name: '大连区', id: '102'}]},
                {name: '铁岭市', id: '104', children: [{name: '沈阳区', id: '101'}, {name: '大连区', id: '102'}]},
                {name: '营口市', id: '105', children: [{name: '沈阳区', id: '101'}, {name: '大连区', id: '102'}]}]
        },{ name: '江苏省', id: '12',
            children: [{name: '无锡市', id: '121', children: [{name: '沈阳区', id: '101'}, {name: '大连区', id: '102'}]},
                { name: '苏州市', id: '122', children: [{name: '沈阳区', id: '101'}, {name: '大连区', id: '102'}]},
                { name: '常州市', id: '123', children: [{name: '沈阳区', id: '101'}, {name: '大连区', id: '102'}]}]
        }, {
            name: '福建省', id: '13',
            children: [{name: '福州市', id: '131', children: [{name: '沈阳区', id: '101'}, {name: '大连区', id: '102'}]}]
        }, {name: '云南省', id: '14',
            children: [{name: '昆明市', id: '141', children: [{name: '沈阳区', id: '101'}, {name: '大连区', id: '102'}]}]
        }
    ],
    dateFullSelect: [{
        '1960': {name: '1960年'},
        '1961': {name: '1961年'},
        '1962': {name: '1962年'},
        '1963': {name: '1963年'},
        '1964': {name: '1964年'},
        '1965': {name: '1965年'},
        '1966': {name: '1966年'},
        '1967': {name: '1967年'},
        '1968': {name: '1968年'},
        '1969': {name: '1969年'},
        '1970': {name: '1970年'},
        '1971': {name: '1971年'},
        '1972': {name: '1972年'},
        '1973': {name: '1973年'},
        '1974': {name: '1974年'},
        '1975': {name: '1975年'},
        '1976': {name: '1976年'},
        '1977': {name: '1977年'},
        '1978': {name: '1978年'},
        '1979': {name: '1979年'},
        '1980': {name: '1980年'},
        '1981': {name: '1981年'},
        '1982': {name: '1982年'},
        '1983': {name: '1983年'},
        '1984': {name: '1984年'},
        '1985': {name: '1985年'},
        '1986': {name: '1986年'},
        '1987': {name: '1987年'},
        '1988': {name: '1988年'},
        '1989': {name: '1989年'},
        '1990': {name: '1990年'},
        '1991': {name: '1991年'},
        '1992': {name: '1992年'},
        '1993': {name: '1993年'},
        '1994': {name: '1994年'},
        '1995': {name: '1995年'},
        '1996': {name: '1996年'},
        '1997': {name: '1997年'},
        '1998': {name: '1998年'},
        '1999': {name: '1999年'},
        '2000': {name: '2000年'},
        '2001': {name: '2001年'},
        '2002': {name: '2002年'},
        '2003': {name: '2003年'},
        '2004': {name: '2004年'},
        '2005': {name: '2005年'},
        '2006': {name: '2006年'},
        '2007': {name: '2007年'},
        '2008': {name: '2008年'},
        '2009': {name: '2009年'},
        '2010': {name: '2010年'},
        '2011': {name: '2011年'},
        '2012': {name: '2012年'},
        '2013': {name: '2013年'},
        '2014': {name: '2014年'},
        '2015': {name: '2015年'},
        '2016': {name: '2016年'},
        '2017': {name: '2017年'},
        '2018': {name: '2018年'},
        '2019': {name: '2019年'},
        '2020': {name: '2020年'},
        '2021': {name: '2021年'},
        '2022': {name: '2022年'},
        '2023': {name: '2023年'},
        '2024': {name: '2024年'},
        '2025': {name: '2025年'},
        '2026': {name: '2026年'},
        '2027': {name: '2027年'},
        '2028': {name: '2028年'},
        '2029': {name: '2029年'},
        '2030': {name: '2030年'}
    },
    {
        '1': {name: '1月'},
        '2': {name: '2月'},
        '3': {name: '3月'},
        '4': {name: '4月'},
        '5': {name: '5月'},
        '6': {name: '6月'},
        '7': {name: '7月'},
        '8': {name: '8月'},
        '9': {name: '9月'},
        '10': {name: '10月'},
        '11': {name: '11月'},
        '12': {name: '12月'}
    },
    {
        '1': {name: '1日'},
        '2': {name: '2日'},
        '3': {name: '3日'},
        '4': {name: '4日'},
        '5': {name: '5日'},
        '6': {name: '6日'},
        '7': {name: '7日'},
        '8': {name: '8日'},
        '9': {name: '9日'},
        '10': {name: '10日'},
        '11': {name: '11日'},
        '12': {name: '12日'},
        '13': {name: '13日'},
        '14': {name: '14日'},
        '15': {name: '15日'},
        '16': {name: '16日'},
        '17': {name: '17日'},
        '18': {name: '18日'},
        '19': {name: '19日'},
        '20': {name: '20日'},
        '21': {name: '21日'},
        '22': {name: '22日'},
        '23': {name: '23日'},
        '24': {name: '24日'},
        '25': {name: '25日'},
        '26': {name: '26日'},
        '27': {name: '27日'},
        '28': {name: '28日'},
        '29': {name: '29日'},
        '30': {name: '30日'},
        '31': {name: '31日'},
    }],
}
